version: '3.1'

services:

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 2301:8080

  oegs-wpc-db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: oegs
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: oegs-db
